server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: on_param
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tom-spring-kotlin
  datasource:
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    url: jdbc:postgresql://${DATABASE_HOST:host}:${DATABASE_PORT:port}/${DATABASE_NAME:database}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:port.example.com}
    username: ${MAIL_USERNAME:username.example.com}
    password: ${MAIL_PASSWORD:password.example.com}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"

springdoc:
  api-docs:
    enabled: true
    path: "/api/v1/api-docs"
  swagger-ui:
    path: "/api/v1/swagger-ui.html"
    config-url: "/api/v1/api-docs/swagger-config"
    disable-swagger-default-url: true
    url: "/api/open-api.yml"

jwt:
  secret-key: ${JWT_SECRET_KEY:jwtKey}