openapi: 3.0.1
info:
  title: Tom Kotlin APIs
  description: Grocery Restful APIs V1
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: development
  - url: https://tom-kotlin.prod.com/
    description: prod
security:
  - BearerAuth: []
